apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  labels:
    type: local
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 500Mi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath: # local과의 차이: hostPath는 폴더를, local은 디스크나 파티션을 마운트하는 것.
    path: /mnt/data